apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    name: kafka 
spec:
  ports:
  - name: kafka-port
    port: 9092
    protocol: TCP
    targetPort: 9092 
  selector:
    name: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: springkafkaprod
spec:
  type: LoadBalancer
  ports:
  - name: springkafka-port 
    port: 8088 
    protocol: TCP
    targetPort: 8088 
  selector:
    name: springkafkaprod
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    name: zookeeper
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
    targetPort: 2181 
  - name: follower
    port: 2888
    protocol: TCP
    targetPort: 2888 
  - name: leader
    port: 3888
    protocol: TCP
    targetPort: 3888 
  selector:
    name: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  ports:
  - name: cql
    port: 9042
    protocol: TCP
    targetPort: 9042 
  selector:
    app: cassandra
